# Generated by Django 4.2.4 on 2023-11-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField(max_length=120)),
                ('author_mail', models.EmailField(blank=True, max_length=254)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('com_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
    ]
