# Generated by Django 4.2.4 on 2023-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tag_post_post_draft_comment_post_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(max_length=120, verbose_name='Your name:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_mail',
            field=models.EmailField(max_length=254, verbose_name='Your e-mail:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_content',
            field=models.TextField(verbose_name='Your comment:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(verbose_name='Post content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(default=None, related_name='posts', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=120, verbose_name='Post title'),
        ),
    ]
